name: Android Debug

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**'
    - '.gitignore'
    - 'README.md'
    - 'LICENSE'
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build app
      run: ./gradlew build

    - name: Upload apk to a release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          app/build/outputs/apk/release/*.apk
          app/build/outputs/apk/debug/*.apk
        tag_name: test
