name: Android Debug

on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**'
    - '.gitignore'
    - 'README.md'
    - 'LICENSE'
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build app
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: app/build/outputs/apk/debug/*.apk
